/**
 * script.js — Dynamic content for your research portfolio
 *
 * JAVASCRIPT FOR PYTHON PROGRAMMERS:
 *
 * Key similarities:
 *   - async/await syntax is essentially identical to Python's asyncio
 *   - Arrays ≈ Python lists; Objects ≈ Python dicts
 *   - map(), filter(), reduce() ≈ Python's list comprehensions
 *
 * Key differences:
 *   - Use const (immutable binding) and let (mutable). Never use var (legacy).
 *   - The "DOM" (Document Object Model) is the browser's live tree of your HTML.
 *     You query and mutate it to update the page without reloading.
 *   - fetch() doesn't throw on HTTP errors (unlike Python's requests) — check .ok
 *   - === is strict equality (checks type AND value). == is loose and causes bugs.
 */

// ============================================================================
// CONFIGURATION — Edit these before deploying
// ============================================================================
const CONFIG = {
  // Your 16-digit ORCID iD: https://orcid.org/my-orcid
  orcidId: "0000-0000-0000-0000",
  // Your name as it appears in author lists (for bold highlighting)
  yourName: "Your Name",
  // Path to the JSON file generated by the GitHub Action (Google Scholar fallback)
  localPublicationsFile: "data/publications.json",
};


// ============================================================================
// UTILITY: Set current year in footer
// ============================================================================
document.getElementById("year").textContent = new Date().getFullYear();


// ============================================================================
// ORCID API INTEGRATION
//
// The ORCID Public API requires no authentication for public profiles.
// It supports CORS, so the browser can call it directly (no server needed).
// Docs: https://pub.orcid.org/
// ============================================================================

/**
 * Fetches all works from an ORCID profile.
 * Uses two-step approach: summary list first, then bulk detail fetch.
 */
async function fetchPublicationsFromORCID(orcidId) {
  const headers = { "Accept": "application/json" };
  const base = "https://pub.orcid.org/v3.0";

  // Step 1: fetch the summary list
  const res = await fetch(`${base}/${orcidId}/works`, { headers });
  if (!res.ok) throw new Error(`ORCID error ${res.status}`);
  const data = await res.json();

  // ORCID groups works by DOI — one group per unique paper
  const groups = data?.group ?? [];
  if (groups.length === 0) return [];

  // Get the "preferred" put-code from each group (highest display-index)
  const putCodes = groups.map(group => {
    const summaries = group["work-summary"] || [];
    summaries.sort((a, b) => b["display-index"] - a["display-index"]);
    return summaries[0]?.["put-code"];
  }).filter(Boolean);

  // Step 2: fetch full details in batches of 50 (ORCID API limit)
  const allWorks = [];
  for (let i = 0; i < putCodes.length; i += 50) {
    const batch = putCodes.slice(i, i + 50);
    const batchRes = await fetch(`${base}/${orcidId}/works/${batch.join(",")}`, { headers });
    if (!batchRes.ok) continue;
    const batchData = await batchRes.json();
    const works = batchData?.bulk?.map(item => item?.work).filter(Boolean) ?? [];
    allWorks.push(...works);
  }

  return allWorks.map(normalizeORCIDWork).filter(Boolean);
}

/**
 * Converts a raw ORCID work object to our internal format.
 * Keeping this separate makes it easy to swap in a different API later.
 */
function normalizeORCIDWork(work) {
  if (!work) return null;

  const title  = work?.["work-title"]?.title?.value ?? "Untitled";
  const year   = work?.["publication-date"]?.year?.value ?? null;
  const venue  = work?.["journal-title"]?.value ?? null;

  // Extract DOI from the external-ids array
  const extIds = work?.["external-ids"]?.["external-id"] ?? [];
  const doi    = extIds.find(id => id["external-id-type"] === "doi")?.["external-id-value"] ?? null;
  const url    = doi ? `https://doi.org/${doi}` : (work?.url?.value ?? null);

  // Extract author names from contributors
  const authors = (work?.contributors?.contributor ?? [])
    .filter(c => c?.["contributor-attributes"]?.["contributor-role"] === "author")
    .map(c => c?.["credit-name"]?.value ?? "")
    .filter(Boolean);

  const pubType = mapORCIDType(work?.type ?? "");

  return { title, year, venue, doi, url, authors, pubType };
}

function mapORCIDType(t) {
  return {
    "journal-article":      "journal-article",
    "conference-paper":     "conference-paper",
    "conference-abstract":  "conference-paper",
    "preprint":             "preprint",
    "working-paper":        "preprint",
  }[t] ?? "other";
}


// ============================================================================
// FALLBACK: publications.json generated by the GitHub Action
// (Contains Google Scholar data + any manual entries)
// ============================================================================

async function loadLocalPublications() {
  try {
    const res = await fetch(CONFIG.localPublicationsFile);
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;  // File doesn't exist yet — that's fine on first run
  }
}

/**
 * Merge ORCID and local publications, deduplicating by DOI.
 * ORCID is treated as authoritative; local data fills in anything missing.
 */
function mergePublications(orcidPubs, localPubs) {
  if (!localPubs) return orcidPubs;

  // Build a Set of DOIs from ORCID data for fast lookup
  // Set is equivalent to Python's set() — O(1) membership testing
  const orcidDOIs = new Set(orcidPubs.map(p => p.doi).filter(Boolean));

  // Add local publications that aren't already in ORCID results
  const extras = localPubs.filter(p => !p.doi || !orcidDOIs.has(p.doi));
  return [...orcidPubs, ...extras];
}


// ============================================================================
// RENDER PUBLICATIONS TO DOM
//
// "Rendering" = generating HTML strings and injecting them into the DOM.
// This is the client-side equivalent of server-side template rendering
// (like Jinja2), but happening live in the browser.
// ============================================================================

/**
 * Builds and injects publication cards into #pub-list.
 * @param {Array} publications - Array of normalized publication objects
 */
function renderPublications(publications) {
  const container = document.getElementById("pub-list");
  if (!container) return;

  if (publications.length === 0) {
    container.innerHTML = `
      <div class="error-state">
        <p>No publications found. Make sure your ORCID profile is public and your iD is correct.</p>
      </div>`;
    return;
  }

  // Sort by year descending (most recent first)
  publications.sort((a, b) => (b.year ?? 0) - (a.year ?? 0));

  // innerHTML: a string of HTML you set as the content of an element.
  // Template literals (backtick strings) support multi-line strings and
  // ${expression} interpolation — equivalent to Python's f-strings.
  container.innerHTML = publications.map(pub => buildPubCard(pub)).join("\n");

  // Store the full list on the container element for filtering
  // (We can attach arbitrary properties to DOM elements — they're just objects)
  container._allPublications = publications;
}

/**
 * Builds the HTML string for a single publication card.
 * Returns a string; does not touch the DOM directly (pure function).
 */
function buildPubCard(pub) {
  // Highlight the user's own name in the author list
  const authorStr = pub.authors.length > 0
    ? pub.authors.map(a => {
        // Check if this author name contains the user's name
        const isMe = a.toLowerCase().includes(CONFIG.yourName.toLowerCase());
        return isMe ? `<span class="own-name">${escapeHTML(a)}</span>` : escapeHTML(a);
      }).join(", ")
    : "Authors unavailable";

  const titleContent = pub.url
    ? `<a href="${pub.url}" target="_blank" rel="noopener noreferrer">${escapeHTML(pub.title)}</a>`
    : escapeHTML(pub.title);

  // Map our type keys to display labels
  const typeLabels = {
    "journal-article":  "Journal",
    "conference-paper": "Conference",
    "preprint":         "Preprint",
    "other":            "Other",
  };
  const typeLabel = typeLabels[pub.pubType] ?? pub.pubType;

  return `
    <article class="pub-card" data-type="${pub.pubType}">
      <div class="pub-year">${pub.year ?? "—"}</div>
      <div class="pub-body">
        <p class="pub-title">${titleContent}</p>
        ${pub.venue ? `<p class="pub-venue">${escapeHTML(pub.venue)}</p>` : ""}
        <p class="pub-authors">${authorStr}</p>
        <div class="pub-tags">
          <span class="pub-tag">${typeLabel}</span>
          ${pub.doi ? `<span class="pub-tag">DOI: ${escapeHTML(pub.doi)}</span>` : ""}
        </div>
      </div>
    </article>`;
}

/**
 * Sanitize user-provided strings before injecting into HTML.
 *
 * WHY THIS MATTERS: If you inject untrusted text directly into innerHTML,
 * a malicious string like <script>stealCookies()</script> would execute.
 * This is called an XSS (Cross-Site Scripting) attack.
 *
 * escapeHTML() converts special HTML characters to their "entity" equivalents,
 * so they render as literal text rather than being parsed as HTML.
 */
function escapeHTML(str) {
  if (typeof str !== "string") return String(str);
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}


// ============================================================================
// PUBLICATION FILTERING
//
// "Event-driven programming": instead of running top-to-bottom, the program
// waits for events (clicks, keypresses, scroll) and calls "event handler"
// functions in response. This is how all interactive UIs work.
// ============================================================================

// querySelectorAll returns a NodeList — we spread it into a real Array
// so we can use Array methods like .forEach() on it.
const filterButtons = [...document.querySelectorAll(".filter-btn")];

filterButtons.forEach(btn => {
  // addEventListener(event, handler) registers a function to call when
  // the event fires on this element. "click" fires on mouse click or keyboard Enter.
  btn.addEventListener("click", () => {
    // "() =>" is an arrow function — equivalent to Python's lambda, but more powerful.
    // Arrow functions capture the surrounding "this" context (unlike regular functions).

    // Update active state on buttons
    filterButtons.forEach(b => b.classList.remove("active"));
    btn.classList.add("active");
    // classList gives access to the element's CSS classes as an object with
    // add(), remove(), toggle(), contains() methods.

    const filter = btn.dataset.filter;
    // dataset mirrors HTML data-* attributes as a JavaScript object.
    // <button data-filter="preprint"> → btn.dataset.filter === "preprint"

    const container = document.getElementById("pub-list");
    if (!container) return;

    // querySelectorAll returns a NodeList (live collection of DOM elements)
    // We spread it into an Array to use forEach.
    const cards = [...container.querySelectorAll(".pub-card")];

    cards.forEach(card => {
      // Toggle visibility based on whether the card's type matches the filter.
      // style.display directly sets the CSS display property on the element.
      if (filter === "all" || card.dataset.type === filter) {
        card.style.display = "";  // empty string resets to the stylesheet default
      } else {
        card.style.display = "none";
      }
    });
  });
});


// ============================================================================
// NAVBAR SCROLL BEHAVIOR
// ============================================================================

// IntersectionObserver watches whether elements enter/leave the viewport.
// This is far more performant than listening to the "scroll" event,
// which fires dozens of times per second.
const heroSection = document.querySelector(".hero");
if (heroSection) {
  const navObserver = new IntersectionObserver(
    (entries) => {
      const navbar = document.querySelector(".navbar");
      if (!navbar) return;
      // If hero is NOT intersecting (scrolled past), add the "scrolled" class
      navbar.classList.toggle("navbar--scrolled", !entries[0].isIntersecting);
    },
    { threshold: 0.1 }  // trigger when 10% of hero is visible/invisible
  );
  navObserver.observe(heroSection);
}


// ============================================================================
// MAIN ENTRY POINT
//
// In Python, you'd use: if __name__ == "__main__": main()
// In browser JavaScript, we call the async main function directly.
// The IIFE (Immediately Invoked Function Expression) pattern wraps async code
// at the top level, since top-level await isn't universally supported.
// ============================================================================

(async function main() {
  const pubContainer = document.getElementById("pub-list");
  if (!pubContainer) return;

  try {
    // Run ORCID fetch and local file fetch concurrently with Promise.all()
    // This is equivalent to Python's asyncio.gather() — both requests fire
    // simultaneously rather than sequentially, saving time.
    const [orcidPubs, localPubs] = await Promise.all([
      fetchPublicationsFromORCID(CONFIG.orcidId).catch(err => {
        console.warn("ORCID fetch failed:", err.message);
        return [];
      }),
      loadLocalPublications(),
    ]);

    const merged = mergePublications(orcidPubs, localPubs ?? []);
    renderPublications(merged);

  } catch (err) {
    console.error("Publication loading failed:", err);
    pubContainer.innerHTML = `
      <div class="error-state">
        <p>Could not load publications. Check your ORCID ID in script.js.</p>
        <p style="font-size:0.8rem; margin-top:0.5rem; opacity:0.6;">${escapeHTML(err.message)}</p>
      </div>`;
  }
})();
